name: Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag monisahmedrizvi/course-api-frontend:$(date +%s)
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push image to Docker Hub
        run: |
          docker push monisahmedrizvi/course-api-frontend:$(date +%s)
          docker tag monisahmedrizvi/course-api-frontend:$(date +%s) moinsahmedrizvi/course-api-frontend:latest
          docker push monisahmedrizvi/course-api-frontend:latest
